/**
 * collection of cliënts, dentists and assistants
 * first person is sick
 *
 * list of basic appointments
 */

export let clients = [
  {
    id: 1,
    gender: "Female",
    first_name: "Blythe",
    last_name: "Citron",
    birthyear: 2000,
    phone: "+212 (104) 839-6547",
    email: "bblythe0@youku.com",
    sick: true,
  },
  {
    id: 2,
    gender: "Female",
    first_name: "Gizela",
    last_name: "Fuscia",
    birthyear: 2000,
    phone: "+380 (896) 586-0572",
    email: "gwhitwood1@shareasale.com",
    sick: false,
  },
  {
    id: 3,
    gender: "Female",
    first_name: "Selle",
    last_name: "Indigo",
    birthyear: 2006,
    phone: "+86 (767) 294-2538",
    email: "sgrinikhin2@senate.gov",
    sick: false,
  },
  {
    id: 4,
    gender: "Female",
    first_name: "Eward",
    last_name: "Coffee",
    birthyear: 2010,
    phone: "+86 (205) 339-2427",
    email: "eduggary3@posterous.com",
    sick: false,
  },
  {
    id: 5,
    gender: "Female",
    first_name: "Cloe",
    last_name: "Copper",
    birthyear: 1999,
    phone: "+47 (318) 606-1800",
    email: "cclemendot4@livejournal.com",
    sick: false,
  },
  {
    id: 6,
    gender: "Male",
    first_name: "Denyse",
    last_name: "Turquoise",
    birthyear: 2013,
    phone: "+62 (512) 446-4861",
    email: "drickhuss5@springer.com",
    sick: false,
  },
  {
    id: 7,
    gender: "Male",
    first_name: "Sheridan",
    last_name: "Cream",
    birthyear: 2012,
    phone: "+380 (546) 811-4487",
    email: "sleadstone6@sciencedirect.com",
    sick: false,
  },
  {
    id: 8,
    gender: "Male",
    first_name: "Valaria",
    last_name: "Crimson",
    birthyear: 1998,
    phone: "+7 (927) 753-5567",
    email: "vtonna7@nasa.gov",
    sick: false,
  },
  {
    id: 9,
    gender: "Male",
    first_name: "Mildred",
    last_name: "Purple",
    birthyear: 2006,
    phone: "+62 (653) 841-0843",
    email: "mmitchelmore8@google.co.uk",
    sick: false,
  },
  {
    id: 10,
    gender: "Female",
    first_name: "Vonnie",
    last_name: "Pink",
    birthyear: 1986,
    phone: "+55 (787) 497-1914",
    email: "vivan9@github.io",
    sick: false,
  },
  {
    id: 11,
    gender: "Male",
    first_name: "Stanton",
    last_name: "Goldenrod",
    birthyear: 1994,
    phone: "+62 (781) 575-2777",
    email: "sneljesa@nbcnews.com",
    sick: false,
  },
  {
    id: 12,
    gender: "Female",
    first_name: "Manya",
    last_name: "Purple",
    birthyear: 2004,
    phone: "+31 (498) 156-5105",
    email: "mmedlingb@free.fr",
    sick: false,
  },
  {
    id: 13,
    gender: "Female",
    first_name: "Beret",
    last_name: "Eggshell",
    birthyear: 1975,
    phone: "+49 (541) 542-4067",
    email: "bdionisoc@illinois.edu",
    sick: false,
  },
  {
    id: 14,
    gender: "Female",
    first_name: "Ola",
    last_name: "Turquoise",
    birthyear: 1997,
    phone: "+86 (529) 218-7246",
    email: "olockeryd@un.org",
    sick: false,
  },
  {
    id: 15,
    gender: "Female",
    first_name: "Kahlil",
    last_name: "Firebrick",
    birthyear: 2005,
    phone: "+63 (194) 185-2043",
    email: "kathridgee@businessweek.com",
    sick: false,
  },
  {
    id: 16,
    gender: "Female",
    first_name: "Abel",
    last_name: "Teal",
    birthyear: 2001,
    phone: "+7 (330) 986-5193",
    email: "adalgarnof@nytimes.com",
    sick: false,
  },
  {
    id: 17,
    gender: "Genderfluid",
    first_name: "Ethelred",
    last_name: "Green",
    birthyear: 1998,
    phone: "+505 (568) 770-6848",
    email: "ecomussog@auda.org.au",
    sick: false,
  },
  {
    id: 18,
    gender: "Male",
    first_name: "Charmian",
    last_name: "Bisque",
    birthyear: 2011,
    phone: "+62 (958) 450-6178",
    email: "cmatulah@list-manage.com",
    sick: false,
  },
  {
    id: 19,
    gender: "Bigender",
    first_name: "Sven",
    last_name: "Frostbite",
    birthyear: 1997,
    phone: "+57 (255) 668-6701",
    email: "smccordi@gov.uk",
    sick: false,
  },
  {
    id: 20,
    gender: "Female",
    first_name: "Merrili",
    last_name: "Coral",
    birthyear: 2008,
    phone: "+381 (833) 718-2850",
    email: "mcalbreathj@digg.com",
    sick: false,
  },
  {
    id: 21,
    gender: "Female",
    first_name: "Clarke",
    last_name: "Capri",
    birthyear: 2003,
    phone: "+351 (833) 303-8328",
    email: "cjakubowiczk@acquirethisname.com",
    sick: false,
  },
  {
    id: 22,
    gender: "Male",
    first_name: "Ilse",
    last_name: "Carmine",
    birthyear: 1991,
    phone: "+7 (446) 740-2512",
    email: "irottgersl@chicagotribune.com",
    sick: false,
  },
  {
    id: 23,
    gender: "Genderqueer",
    first_name: "Lawry",
    last_name: "Bone",
    birthyear: 2009,
    phone: "+48 (407) 804-6293",
    email: "lrevettm@example.com",
    sick: false,
  },
  {
    id: 24,
    gender: "Female",
    first_name: "Jackson",
    last_name: "Mauv",
    birthyear: 1996,
    phone: "+62 (235) 133-5072",
    email: "jyockneyn@cafepress.com",
    sick: false,
  },
  {
    id: 25,
    gender: "Female",
    first_name: "Eleonora",
    last_name: "Teal",
    birthyear: 2012,
    phone: "+55 (818) 516-8123",
    email: "emarshfieldo@house.gov",
    sick: false,
  },
  {
    id: 26,
    gender: "Male",
    first_name: "Fitz",
    last_name: "Violet",
    birthyear: 1991,
    phone: "+62 (898) 898-3471",
    email: "ffrightp@gizmodo.com",
    sick: false,
  },
  {
    id: 27,
    gender: "Female",
    first_name: "Fax",
    last_name: "Orange",
    birthyear: 2006,
    phone: "+27 (665) 401-8263",
    email: "ftunacliftq@answers.com",
    sick: false,
  },
  {
    id: 28,
    gender: "Male",
    first_name: "Binnie",
    last_name: "Purple",
    birthyear: 1993,
    phone: "+86 (203) 504-8395",
    email: "byitzhakr@symantec.com",
    sick: false,
  },
  {
    id: 29,
    gender: "Female",
    first_name: "Vinnie",
    last_name: "Bittersweet",
    birthyear: 1999,
    phone: "+351 (931) 913-9072",
    email: "vambrozewiczs@twitter.com",
    sick: false,
  },
  {
    id: 30,
    gender: "Female",
    first_name: "Judas",
    last_name: "Red",
    birthyear: 2004,
    phone: "+591 (791) 116-7784",
    email: "jcreffieldt@surveymonkey.com",
    sick: false,
  },
  {
    id: 31,
    gender: "Female",
    first_name: "Danya",
    last_name: "Brown",
    birthyear: 1962,
    phone: "+1 (913) 605-2892",
    email: "dewersu@wunderground.com",
    sick: false,
  },
  {
    id: 32,
    gender: "Male",
    first_name: "Leonhard",
    last_name: "Bronze",
    birthyear: 2006,
    phone: "+351 (849) 562-6319",
    email: "lpidgeleyv@time.com",
    sick: false,
  },
  {
    id: 33,
    gender: "Male",
    first_name: "Claybourne",
    last_name: "Blond",
    birthyear: 2000,
    phone: "+55 (385) 618-4602",
    email: "cmeatcherw@etsy.com",
    sick: false,
  },
  {
    id: 34,
    gender: "Female",
    first_name: "Anabella",
    last_name: "Camel",
    birthyear: 2008,
    phone: "+81 (296) 834-5651",
    email: "adufferx@rakuten.co.jp",
    sick: false,
  },
  {
    id: 35,
    gender: "Female",
    first_name: "Claire",
    last_name: "Yellow",
    birthyear: 2010,
    phone: "+355 (542) 583-6786",
    email: "cdissmany@discovery.com",
    sick: false,
  },
  {
    id: 36,
    gender: "Female",
    first_name: "Millard",
    last_name: "Buff",
    birthyear: 2012,
    phone: "+507 (995) 689-2067",
    email: "mstowerz@delicious.com",
    sick: false,
  },
  {
    id: 37,
    gender: "Female",
    first_name: "Nathanial",
    last_name: "Charcoal",
    birthyear: 2008,
    phone: "+63 (593) 526-6704",
    email: "nronchetti10@homestead.com",
    sick: false,
  },
  {
    id: 38,
    gender: "Male",
    first_name: "Vivie",
    last_name: "Auburn",
    birthyear: 1992,
    phone: "+64 (316) 464-3064",
    email: "vandover11@vinaora.com",
    sick: false,
  },
  {
    id: 39,
    gender: "Male",
    first_name: "Sollie",
    last_name: "Aquamarine",
    birthyear: 2002,
    phone: "+234 (473) 380-9524",
    email: "sjamme12@xinhuanet.com",
    sick: false,
  },
  {
    id: 40,
    gender: "Female",
    first_name: "Shem",
    last_name: "Beaver",
    birthyear: 1995,
    phone: "+54 (950) 160-1410",
    email: "sferminger13@dropbox.com",
    sick: false,
  },
  {
    id: 41,
    gender: "Male",
    first_name: "Celestine",
    last_name: "Yellow",
    birthyear: 1998,
    phone: "+62 (203) 658-8007",
    email: "cnorman14@lulu.com",
    sick: false,
  },
  {
    id: 42,
    gender: "Female",
    first_name: "Fredek",
    last_name: "Teal",
    birthyear: 2011,
    phone: "+970 (325) 846-3184",
    email: "fbraine15@xrea.com",
    sick: false,
  },
  {
    id: 43,
    gender: "Female",
    first_name: "Edmon",
    last_name: "Blue",
    birthyear: 2010,
    phone: "+86 (652) 417-1865",
    email: "econichie16@canalblog.com",
    sick: false,
  },
  {
    id: 44,
    gender: "Female",
    first_name: "Louisette",
    last_name: "Avocado",
    birthyear: 2000,
    phone: "+55 (542) 220-0468",
    email: "lhuish17@nationalgeographic.com",
    sick: false,
  },
  {
    id: 45,
    gender: "Male",
    first_name: "Myrwyn",
    last_name: "Aquamarine",
    birthyear: 1998,
    phone: "+98 (630) 386-5445",
    email: "mtrighton18@prlog.org",
    sick: false,
  },
  {
    id: 46,
    gender: "Female",
    first_name: "Kamillah",
    last_name: "Khaki",
    birthyear: 2004,
    phone: "+44 (239) 578-0525",
    email: "kkite19@mediafire.com",
    sick: false,
  },
  {
    id: 47,
    gender: "Male",
    first_name: "Jehu",
    last_name: "Blue-Gray",
    birthyear: 2006,
    phone: "+1 (215) 848-0963",
    email: "jroad1a@macromedia.com",
    sick: false,
  },
  {
    id: 48,
    gender: "Male",
    first_name: "Grayce",
    last_name: "Red",
    birthyear: 2008,
    phone: "+55 (390) 877-5878",
    email: "gratlee1b@wiley.com",
    sick: false,
  },
  {
    id: 49,
    gender: "Male",
    first_name: "Morie",
    last_name: "Byzantine",
    birthyear: 2006,
    phone: "+62 (556) 450-4869",
    email: "mlyford1c@si.edu",
    sick: false,
  },
  {
    id: 50,
    gender: "Male",
    first_name: "Abbi",
    last_name: "Corn",
    birthyear: 2006,
    phone: "+386 (543) 758-9614",
    email: "arojel1d@i2i.jp",
    sick: false,
  },
];

export let dentists = [
  {
    id: 51,
    gender: "Female",
    first_name: "Jobi",
    last_name: "Beige",
    birthyear: 1999,
    phone: "+86 (732) 980-9139",
    email: "jtopley1e@dentistcompanybvt.com",
    sick: true,
  },
  {
    id: 52,
    gender: "Female",
    first_name: "Bobbi",
    last_name: "Khaki",
    birthyear: 1986,
    phone: "+234 (235) 702-2251",
    email: "bjohnes1f@dentistcompanybvt.com",
    sick: false,
  },
  {
    id: 53,
    gender: "Female",
    first_name: "Erick",
    last_name: "Turquoise",
    birthyear: 1980,
    phone: "+33 (361) 159-5749",
    email: "ewoolerton1g@dentistcompanybvt.com",
    sick: false,
  },
  {
    id: 54,
    gender: "Male",
    first_name: "Tandie",
    last_name: "Puce",
    birthyear: 1994,
    phone: "+503 (274) 402-6895",
    email: "tkearle1h@dentistcompanybvt.com",
    sick: false,
  },
  {
    id: 55,
    gender: "Male",
    first_name: "Wolfgang",
    last_name: "Indigo",
    birthyear: 1984,
    phone: "+41 (288) 492-3675",
    email: "wmyrie1i@dentistcompanybvt.com",
    sick: false,
  },
];

export let assistants = [
  {
    id: 61,
    gender: "Male",
    first_name: "Carlin",
    last_name: "Blush",
    birthyear: 1993,
    phone: "+86 (197) 522-9144",
    email: "cfellows1o@dentistcompanybvt.com",
    sick: true,
  },
  {
    id: 62,
    gender: "Female",
    first_name: "Port",
    last_name: "Azure",
    birthyear: 1988,
    phone: "+1 (583) 228-8123",
    email: "pyeld1p@miitbeian.dentistcompanybvt.com",
    sick: false,
  },
];

export let appointments = [
  {
    id: 123,
    dayOfMonth: 1,
    time: 16,
    patient: "Lieke Kramer",
    assistant: "Johanneke van Loon",
    dentist: "Lotte Vos",
  },
];

// export function getDentists() {
//   return dentists;
// }

// export function getClients() {
//   return clients;
// }

// export function getAssistants() {
//   return assistants;
// }

// export function getAppointments() {
//   return appointments;
// }
